In [1]:
#IMPORTING PACKAGES

#glob to compile scraped dataset from csv file exports
import glob

#pandas to visualise glob success
import pandas as pd

In [2]:
#GLOB FILES

#get list of webscrape batch result csv files in the working directory as a list
files = glob.glob('*.{}'.format('csv'))
files

['action_MetaCritScores.csv',
 'adventure_MetaCritScores.csv',
 'fighting_MetaCritScores.csv',
 'first-person_MetaCritScores.csv',
 'flight_MetaCritScores.csv',
 'party_MetaCritScores.csv',
 'platformer_MetaCritScores.csv',
 'puzzle_MetaCritScores.csv',
 'racing_MetaCritScores.csv',
 'real-time_MetaCritScores.csv',
 'role-playing_MetaCritScores.csv',
 'simulation_MetaCritScores.csv',
 'sports_MetaCritScores.csv',
 'strategy_MetaCritScores.csv',
 'third-person_MetaCritScores.csv',
 'turn-based_MetaCritScores.csv',
 'wargame_MetaCritScores.csv',
 'wrestling_MetaCritScores.csv']

In [3]:
#COMPILE DATAFRAMES

#create composite dataset by stitching each csv together

#assign empty dataframe to iteratively add to 
mcs = pd.DataFrame()

#loop through csvs in glob list
for file in files:
    
    #import csv and overide temporary variable dataframe
    temp_df = pd.read_csv(file)
    
    #Add the temporary variable dataframe to the bottom of the storage dataframe
    mcs = pd.concat([mcs, temp_df], axis=0, ignore_index = True)
    
#drop column 1 which is the unnamed index from csv exporting
mcs = mcs.iloc[:,1:]
mcs

,position,title,platform,pub_date,rating,genre
0,1,SoulCalibur,Dreamcast,1999-09-08,98,action
1,2,Super Mario Galaxy,Wii,2007-11-12,97,action
2,3,Super Mario Galaxy 2,Wii,2010-05-23,97,action
3,4,Perfect Dark,Nintendo 64,2000-05-22,97,action
4,5,Metroid Prime,GameCube,2002-11-17,97,action
...,...,...,...,...,...,...
36252,105,ECW Anarchy Rulz,Dreamcast,2000-12-30,38,wrestling
36253,106,The Simpsons Wrestling,PlayStation,2001-04-12,32,wrestling
36254,107,Mucha Lucha! Mascaritas of the Lost Code,Game Boy Advance,2003-11-18,26,wrestling
36255,108,Hulk Hogan's Main Event,Xbox 360,2011-10-11,26,wrestling
36256,109,Legends of Wrestling II,Game Boy Advance,2002-11-25,24,wrestling

In [18]:
#CHECKING COMPLETEDNESS

#Use info method to look for equal non-null data and correct data types
mcs.info()

#Note: pub_date column is stored as an object

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36257 entries, 0 to 36256
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   position  36257 non-null  int64
 1   title     36257 non-null  object
 2   platform  36257 non-null  object
 3   pub_date  36257 non-null  object
 4   rating    36257 non-null  int64
 5   genre     36257 non-null  object
dtypes: int64(2), object(4)
memory usage: 1.7+ MB

In [19]:
#PREPARATION

#Convert date-time column to data-time datatype
mcs['pub_date'] = pd.to_datetime(mcs['pub_date'])

#Check pub_date column is stored as datetime
mcs.info()

#Note: datetime assignment will be lost on csv export

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36257 entries, 0 to 36256
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   position  36257 non-null  int64
 1   title     36257 non-null  object
 2   platform  36257 non-null  object
 3   pub_date  36257 non-null  datetime64[ns]
 4   rating    36257 non-null  int64
 5   genre     36257 non-null  object
dtypes: datetime64[ns](1), int64(2), object(3)
memory usage: 1.7+ MB

In [22]:
#Export globbed csv to an output folder and remove pandas artificial index
mcs.to_csv('./output/MetaCritScores.csv', index=False)